import java.util.Scanner;

/**
 * This Driver class is to be used with the RNG class. 
 * This application will create a Random Number Guesser.
 * Receiving a guess and reporting if the guess is the random number that was generated.
 * Narrowing down the choices according to previous guesses and continuing to prompt until guessed correctly
 * 
 * @author Constance Noble
 */
class RandomNumberGuesser {
/**
 * The main method is the program's starting point
 * 
 */
	public static void main(String[] args) {
		
		int highGuess = 99; //holds and initializes the highest guess boundary
		int lowGuess = 0; // holds and initializes the lowest guess boundary
		int randNum; // holds the random number
		int nextGuess; // holds int value of the user's guess
		String playing = ""; // holds the user's decision to play (yes or no)
		Scanner input = new Scanner(System.in); // scanner reference object for reading input from keyboard
		
		System.out.println("This program is a Random Number Guesser Game!"); // prints the application purpose
		System.out.println("-----------------------------------------------");
		
		//This loop executes until player answers "no" to playing again.
		do { 
			randNum = RNG.rand(100); // call rand method to create random int between 0-99, assign the value to randNum int
			System.out.println("Guess the Random Number between 0  and 99"); // prompt user to enter guess
			
			//This loop executes until player guesses the random integer
			do {
				nextGuess = input.nextInt(); //assigns user guess from keyboard into nextGuess
				
				//This loop executes while user's guess is not within range of lowGuess and highGuess
				while((nextGuess>=highGuess || nextGuess<=lowGuess)) {
					RNG.inputValidation(nextGuess, lowGuess, highGuess);
					nextGuess = input.nextInt();
				}
				
				RNG r = new RNG(); // creates RNG object to increment counter
				
				System.out.println("Number of guesses is " + r.getCount());//Prints number of guesses generated by the RNG class to output
				// executes if user's guess is larger than random number
				if(nextGuess > randNum) {
					System.out.println("Your guess is too high"); // prints if user's guess is too high
					highGuess = nextGuess; // assigns highGuess to user's previous guess
					System.out.println("Enter your next guess between " + lowGuess + " and " + highGuess); // prompts user to enter a new guess between lowGuess and the user's previous guess, which is now the boundary
				
				//executes if the user's guess is smaller than random number
				}
				else if(nextGuess < randNum) {
					System.out.println("Your guess is too low");// prints if user's guess is too low
					lowGuess = nextGuess;// assigns lowGuess to user's previous guess
					System.out.println("Enter your next guess between " + lowGuess + " and " + highGuess);// prompts user to enter a new guess between their previous guess and the highGuess
					}
			} while(nextGuess != randNum);
		
			RNG.resetCount();// method provided by the RNG class to reset count variable to 0.
			lowGuess = 0; // assigns lowGuess to zero
			highGuess = 99; // assigns highGuess to 99
			
			System.out.println("Congratulations, you guessed correctly!"); // prints congratulations message to screen
			System.out.println("Try again? (yes or no)?");// asks user if they would like to keep playing
			System.out.println("-----------------------------------------------");
			playing = getAnswer(); // calls getAnswer method and assigns playing to value returned from the method.
			
		} while(playing.equalsIgnoreCase("yes"));
		

		
		System.out.println("Thanks for playing!");//prints thanks for playing to screen
		System.out.println();
		System.out.println();
		System.out.println();
		System.out.println("Constance Noble");// prints author name
	}
	/**
	 * Method used to create a new scanner object
	 * assigns keyboard input into String variable answer
	 * checks if answer is either yes or no ignoring case
	 * @return the answer received from input
	 */
			
	public static String getAnswer() {
		
		Scanner keyboard = new Scanner(System.in);
		String answer = keyboard.nextLine();
			while (!(answer.equalsIgnoreCase("yes")) && !(answer.equalsIgnoreCase("no"))) {
				System.out.println("Answer using only yes or no.");
				answer = keyboard.nextLine();
			}
		return answer;
		
	}
	
	
}

